#!/usr/bin/env python2
#
import sys

gamma = 2.5

print "// Generated by gamma_tab.py, gamma %.3f" % gamma
print "//"
print "static const uint16_t gamma_tab[256] = {"

for i in range(256):
    # apply gamma correction
    #
    ig = int( ((i + 0.5) / 255.5) ** gamma * 65535 + 0.5 )

    if (i % 8 == 0):
        print "   ",

    if (i != 255):
        print "%5d," % ig,
    else:
        print "%5d" % ig,

    if (i % 8 == 7):
        print

print "};"
